### ISSUE TITLE
Notify user when an upgrade is available

### ISSUE THREAD

**Issue by ipmb** [apppackio/apppack#38]
Here's an example from `gh`

https://github.com/cli/cli/blob/c4455297198031b8701544f5fff1b2621e57c454/cmd/gh/main.go#L245-L261

And one from `flyctl` (looks a bit more robust) https://github.com/superfly/flyctl/blob/ac3bf682a43ac6b0dc8586b7a13ae2a766d6893a/internal/command/version/update.go

**Comment by nicolaslara** [comment]
@ipmb Do we assume all users are on mac or linux? Not sure how to upgrade on windows.

**Comment by ipmb** [comment]
No, we shouldn't. The Fly repo has code for handling Windows, but I haven't dug too deep into it.

**Comment by nicolaslara** [comment]
also, do we want to provide a command for upgrading? or let the users do it? flyctl upgrades and gh just notifies

**Comment by ipmb** [comment]
I think just give them the command... there may be a valid reason somebody does _not_ want to upgrade.

**Comment by nicolaslara** [comment]
sounds good. I was thinking of having a command that executes the upgrade and one that checks on every invocation (maybe more like: every 100th invocation or 2 days, whatever happens first). But printing is probably good enough. The users then can do their installation however they prefer

**Comment by nicolaslara** [comment]
Added a PR
